package basics_java_02;

public class CreateClass implements Cloneable {
	int a=10;
	public void add(){
	    System.out.println("Number adding");
	}
	 public static void main(String[] args) throws InstantiationException, IllegalAccessException, CloneNotSupportedException {
	        //creating object with new feature
	        CreateClass cc = new CreateClass();
	        cc.add();
	        System.out.println(cc);

	        //Create object with newInstance
	        try{
	        Class c = Class.forName("createclass.CreateClass");
	            CreateClass ci = (CreateClass) c.newInstance();
	            ci.add();
	            System.out.println(ci);
	        }catch(ClassNotFoundException e){
	            //todo Autogenerated catch block
	            e.printStackTrace();
	        }
	        //Create object with Object.clone()
	        CreateClass objClone = (CreateClass) cc.clone();
	        objClone.add();
	        System.out.println("Object Clone :- "+objClone);
	    }

}
